In [1]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.5.20)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [2]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

In [6]:
# Fetch dataset
apartment_for_rent_classified = fetch_ucirepo(id=555)

# Features and target
X = apartment_for_rent_classified.data.features
y = apartment_for_rent_classified.data.targets

# Combine into one DataFrame
df = pd.concat([X, y], axis=1)

# View result
print(df.head())
print(df.shape)

/usr/local/lib/python3.12/dist-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (0,5,6,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

                 category                            title  \
0  housing/rent/apartment       One BR 507 & 509 Esplanade
1  housing/rent/apartment      Three BR 146 Lochview Drive
2  housing/rent/apartment  Three BR 3101 Morningside Drive
3  housing/rent/apartment            Two BR 209 Aegean Way
4  housing/rent/apartment         One BR 4805 Marquette NE

                                                body amenities bathrooms  \
0  This unit is located at 507 & 509 Esplanade, R...       NaN         1
1  This unit is located at 146 Lochview Drive, Ne...       NaN       1.5
2  This unit is located at 3101 Morningside Drive...       NaN         2
3  This unit is located at 209 Aegean Way, Vacavi...       NaN         1
4  This unit is located at 4805 Marquette NE, Alb...       NaN         1

  bedrooms currency fee  has_photo pets_allowed  ...  price_display  \
0        1      USD  No  Thumbnail         Cats  ...           2195
1        3      USD  No  Thumbnail    Cats,Dogs  ...           1250
2        3      USD  No  Thumbnail          NaN  ...           1395
3        2      USD  No  Thumbnail    Cats,Dogs  ...           1600
4        1      USD  No  Thumbnail    Cats,Dogs  ...            975

  price_type square_feet              address       cityname state latitude  \
0    Monthly         542   507  509 Esplanade  Redondo Beach    CA  33.8520
1    Monthly        1500      146 Lochview Dr   Newport News    VA  37.0867
2    Monthly        1650  3101 Morningside Dr        Raleigh    NC  35.8230
3    Monthly         820       209 Aegean Way      Vacaville    CA  38.3622
4    Monthly         624    4805 Marquette NE    Albuquerque    NM  35.1038

   longitude     source          time
0  -118.3759  RentLingo  1.577360e+09
1   -76.4941  RentLingo  1.577360e+09
2   -78.6438  RentLingo  1.577360e+09
3  -121.9712  RentLingo  1.577360e+09
4  -106.6110  RentLingo  1.577360e+09

[5 rows x 21 columns]
(99826, 21)

In [7]:
df = df.drop(columns=['body', 'title'])

In [8]:
print(df)

                     category  \
0      housing/rent/apartment
1      housing/rent/apartment
2      housing/rent/apartment
3      housing/rent/apartment
4      housing/rent/apartment
...                       ...
99821  housing/rent/apartment
99822  housing/rent/apartment
99823  housing/rent/apartment
99824  housing/rent/apartment
99825  housing/rent/apartment

                                               amenities bathrooms bedrooms  \
0                                                    NaN         1        1
1                                                    NaN       1.5        3
2                                                    NaN         2        3
3                                                    NaN         1        2
4                                                    NaN         1        1
...                                                  ...       ...      ...
99821  Gym,Parking,Patio/Deck,Playground,Storage,Wood...       1.0      1.0
99822  AC,Cable or Satellite,Clubhouse,Dishwasher,Gym...       2.0      2.0
99823                      Garbage Disposal,Refrigerator       1.0      1.0
99824                                           Gym,Pool       1.0      1.0
99825                          Gated,Parking,Wood Floors       1.5      2.0

      currency fee  has_photo pets_allowed   price price_display price_type  \
0          USD  No  Thumbnail         Cats  2195.0          2195    Monthly
1          USD  No  Thumbnail    Cats,Dogs  1250.0          1250    Monthly
2          USD  No  Thumbnail          NaN  1395.0          1395    Monthly
3          USD  No  Thumbnail    Cats,Dogs  1600.0          1600    Monthly
4          USD  No  Thumbnail    Cats,Dogs   975.0           975    Monthly
...        ...  ..        ...          ...     ...           ...        ...
99821      USD  No        Yes          NaN   780.0           780    Monthly
99822      USD  No        Yes    Cats,Dogs   813.0           813    Monthly
99823      USD  No        Yes    Cats,Dogs  1325.0          1325    Monthly
99824      USD  No        Yes    Cats,Dogs   931.0           931    Monthly
99825      USD  No        Yes          NaN  1595.0          1595    Monthly

      square_feet              address       cityname state  latitude  \
0             542   507  509 Esplanade  Redondo Beach    CA   33.8520
1            1500      146 Lochview Dr   Newport News    VA   37.0867
2            1650  3101 Morningside Dr        Raleigh    NC   35.8230
3             820       209 Aegean Way      Vacaville    CA   38.3622
4             624    4805 Marquette NE    Albuquerque    NM   35.1038
...           ...                  ...            ...   ...       ...
99821         605                  NaN        Houston    TX   29.6151
99822         921                  NaN   Jacksonville    FL   30.2254
99823         650                  NaN      San Diego    CA   32.7379
99824         701                  NaN   Huntersville    NC   35.4158
99825         900                  NaN      San Diego    CA   32.7379

       longitude        source          time
0      -118.3759     RentLingo  1.577360e+09
1       -76.4941     RentLingo  1.577360e+09
2       -78.6438     RentLingo  1.577360e+09
3      -121.9712     RentLingo  1.577360e+09
4      -106.6110     RentLingo  1.577360e+09
...          ...           ...           ...
99821   -95.1998  RentDigs.com  1.544186e+09
99822   -81.7579  RentDigs.com  1.544186e+09
99823  -117.0914  RentDigs.com  1.544186e+09
99824   -80.8451  RentDigs.com  1.544186e+09
99825  -117.0914  RentDigs.com  1.544186e+09

[99826 rows x 19 columns]

In [9]:
import re

df['amenities'] = df['amenities'].astype(str).str.replace(r'[^\w\s]', ' ', regex=True)

In [10]:
df.head(10)

,category,amenities,bathrooms,bedrooms,currency,fee,has_photo,pets_allowed,price,price_display,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,housing/rent/apartment,nan,1,1,USD,No,Thumbnail,Cats,2195.0,2195,Monthly,542,507 509 Esplanade,Redondo Beach,CA,33.8520,-118.3759,RentLingo,1.577360e+09
1,housing/rent/apartment,nan,1.5,3,USD,No,Thumbnail,"Cats,Dogs",1250.0,1250,Monthly,1500,146 Lochview Dr,Newport News,VA,37.0867,-76.4941,RentLingo,1.577360e+09
2,housing/rent/apartment,nan,2,3,USD,No,Thumbnail,NaN,1395.0,1395,Monthly,1650,3101 Morningside Dr,Raleigh,NC,35.8230,-78.6438,RentLingo,1.577360e+09
3,housing/rent/apartment,nan,1,2,USD,No,Thumbnail,"Cats,Dogs",1600.0,1600,Monthly,820,209 Aegean Way,Vacaville,CA,38.3622,-121.9712,RentLingo,1.577360e+09
4,housing/rent/apartment,nan,1,1,USD,No,Thumbnail,"Cats,Dogs",975.0,975,Monthly,624,4805 Marquette NE,Albuquerque,NM,35.1038,-106.6110,RentLingo,1.577360e+09
5,housing/rent/apartment,nan,1.5,2,USD,No,Thumbnail,"Cats,Dogs",1250.0,1250,Monthly,965,7801 Marble NE,Albuquerque,NM,35.1038,-106.6110,RentLingo,1.577360e+09
6,housing/rent/apartment,nan,2,2,USD,No,Thumbnail,NaN,1600.0,1600,Monthly,1120,5 Salt Marsh Quay Apartment H,Hampton,VA,37.0451,-76.3664,RentLingo,1.577360e+09
7,housing/rent/apartment,nan,2,2,USD,No,Thumbnail,"Cats,Dogs",1300.0,1300,Monthly,947,11280 W 20th Avenue,Lakewood,CO,39.6894,-105.1119,RentLingo,1.577360e+09
8,housing/rent/apartment,nan,1,2,USD,No,Thumbnail,Dogs,795.0,795,Monthly,600,1427 Lewis St,Charleston,WV,38.3454,-81.6219,RentLingo,1.577360e+09
9,housing/rent/apartment,nan,2,2,USD,No,Thumbnail,NaN,2150.0,2150,Monthly,1005,10201 Remmet Ave,Chatsworth,CA,34.2551,-118.5976,RentLingo,1.577360e+09

In [11]:
# Count nulls per column
df.isnull().sum().sort_values(ascending=False)

# Percentage nulls
(df.isnull().mean() * 100).sort_values(ascending=False)

address          92.040150
pets_allowed     60.739687
cityname          0.305532
state             0.305532
bedrooms          0.127221
bathrooms         0.066115
longitude         0.031054
latitude          0.029051
source            0.006010
time              0.006010
price_display     0.006010
price             0.005009
currency          0.004007
price_type        0.003005
has_photo         0.003005
fee               0.003005
square_feet       0.003005
amenities         0.000000
category          0.000000
dtype: float64

In [12]:
print(df.dtypes)

category          object
amenities         object
bathrooms         object
bedrooms          object
currency          object
fee               object
has_photo         object
pets_allowed      object
price            float64
price_display     object
price_type        object
square_feet       object
address           object
cityname          object
state             object
latitude         float64
longitude        float64
source            object
time             float64
dtype: object

In [13]:
object_cols = df.select_dtypes(include=['object']).columns
print(object_cols)

Index(['category', 'amenities', 'bathrooms', 'bedrooms', 'currency', 'fee',
       'has_photo', 'pets_allowed', 'price_display', 'price_type',
       'square_feet', 'address', 'cityname', 'state', 'source'],
      dtype='object')

In [14]:
print(df['price_display'].head(20))
print(df['price_display'].dtype)

0     2195
1     1250
2     1395
3     1600
4      975
5     1250
6     1600
7     1300
8      795
9     2150
10    1795
11    3195
12    2395
13    7800
14     720
15    2000
16     729
17    1045
18    1800
19    1250
Name: price_display, dtype: object
object

In [15]:
import pandas as pd
import numpy as np

df_clean = df.copy()

# Numeric columns
df_clean['bathrooms'] = pd.to_numeric(df_clean['bathrooms'], errors='coerce')
df_clean['bedrooms'] = pd.to_numeric(df_clean['bedrooms'], errors='coerce')
df_clean['square_feet'] = pd.to_numeric(df_clean['square_feet'], errors='coerce')

# Boolean-like columns
df_clean['fee'] = df_clean['fee'].map({
    'Yes': True,
    'No': False,
    'yes': True,
    'no': False
})

# Unix timestamp -> datetime (if that's what time contains)
df_clean['time'] = pd.to_datetime(
    df_clean['time'],
    unit='s',
    errors='coerce'
)

In [16]:
df_clean.dtypes

category                 object
amenities                object
bathrooms               float64
bedrooms                float64
currency                 object
fee                      object
has_photo                object
pets_allowed             object
price                   float64
price_display            object
price_type               object
square_feet             float64
address                  object
cityname                 object
state                    object
latitude                float64
longitude               float64
source                   object
time             datetime64[ns]
dtype: object

In [17]:
print(df['fee'].value_counts(dropna=False))
print(df['has_photo'].value_counts(dropna=False))
print(df['pets_allowed'].value_counts(dropna=False))
print(df['price_display'].value_counts(dropna=False))

fee
No      99619
Yes       201
NaN         3
1380        1
2150        1
1019        1
Name: count, dtype: int64
has_photo
Yes          56165
Thumbnail    34394
No            9261
NaN              3
1380             1
2150             1
Monthly          1
Name: count, dtype: int64
pets_allowed
NaN               60634
Cats,Dogs         37213
Cats               1848
Dogs                127
Monthly               2
823                   1
Cats,Dogs,None        1
Name: count, dtype: int64
price_display
1350    571
850     542
1200    533
1100    521
950     518
       ...
4495      1
2590      1
685       1
909       1
1314      1
Name: count, Length: 4547, dtype: int64

In [18]:
df[['price', 'price_display']].head(20)

     price price_display
0   2195.0          2195
1   1250.0          1250
2   1395.0          1395
3   1600.0          1600
4    975.0           975
5   1250.0          1250
6   1600.0          1600
7   1300.0          1300
8    795.0           795
9   2150.0          2150
10  1795.0          1795
11  3195.0          3195
12  2395.0          2395
13  7800.0          7800
14   720.0           720
15  2000.0          2000
16   729.0           729
17  1045.0          1045
18  1800.0          1800
19  1250.0          1250

In [19]:
non_numeric = df[
    pd.to_numeric(df['price_display'], errors='coerce').isna()
]

print(non_numeric[['price_display']].drop_duplicates())

             price_display
6729         $1,560 Weekly
6864                   NaN
7245   $275 Monthly|Weekly
50211        $8,500 Weekly
50712      $1,782 - $1,917
50713      $2,882 - $3,312
50731        $810 - $1,025
50733      $2,322 - $2,562
50734      $1,942 - $1,972
50854      $2,472 - $2,682
50862      $1,642 - $1,652
50868      $1,702 - $1,847
50869      $2,612 - $2,792
50870      $2,582 - $2,842
50877      $1,213 - $6,598
50898      $1,682 - $1,762
50906      $1,952 - $1,972
50907      $2,552 - $2,832
50932      $1,538 - $2,529
51258        $820 - $1,020
51266          $820 - $870
51487          $805 - $895
51704      $1,295 - $1,700
51709        $500 - $2,000
51804      $1,999 - $2,109
51951      $2,555 - $2,700
52095      $1,995 - $3,150
52103        $898 - $2,576
75947              Henrico
83607      $1,197 - $2,304
83631        $995 - $1,080
83656      $2,541 - $2,679
83729          $850 Weekly
83824      $2,313 - $2,713

In [20]:
df.loc[75947]

category                    2
amenities                  No
bathrooms           Thumbnail
bedrooms            Cats,Dogs
currency                 1019
fee                      1019
has_photo             Monthly
pets_allowed              823
price                     NaN
price_display         Henrico
price_type                 VA
square_feet           37.6249
address              -77.4948
cityname         RentDigs.com
state              1550831790
latitude                  NaN
longitude                 NaN
source                    NaN
time                      NaN
Name: 75947, dtype: object

In [21]:
df = df.drop(index=75947)

In [22]:
df['category'].value_counts().head(20)

category
housing/rent/apartment            99762
housing/rent/commercial/retail       42
housing/rent                          7
housing/rent/short_term               4
housing/rent/home                     4
housing/rent/condo                    3
Gym                                   1
Parking,Patio/Deck                    1
housing/rent/other                    1
Name: count, dtype: int64

In [23]:
df[df['category'] == '2']

Empty DataFrame
Columns: [category, amenities, bathrooms, bedrooms, currency, fee, has_photo, pets_allowed, price, price_display, price_type, square_feet, address, cityname, state, latitude, longitude, source, time]
Index: []

In [24]:
bad_rows = df[
    pd.to_numeric(df['currency'], errors='coerce').notna()
]

bad_rows

Empty DataFrame
Columns: [category, amenities, bathrooms, bedrooms, currency, fee, has_photo, pets_allowed, price, price_display, price_type, square_feet, address, cityname, state, latitude, longitude, source, time]
Index: []

In [25]:
df['price_display'] = pd.to_numeric(
    df['price_display'],
    errors='coerce'
)

In [26]:
df['price_display'].dtype

dtype('float64')

In [27]:
df[['price', 'price_display']].head(20)

     price  price_display
0   2195.0         2195.0
1   1250.0         1250.0
2   1395.0         1395.0
3   1600.0         1600.0
4    975.0          975.0
5   1250.0         1250.0
6   1600.0         1600.0
7   1300.0         1300.0
8    795.0          795.0
9   2150.0         2150.0
10  1795.0         1795.0
11  3195.0         3195.0
12  2395.0         2395.0
13  7800.0         7800.0
14   720.0          720.0
15  2000.0         2000.0
16   729.0          729.0
17  1045.0         1045.0
18  1800.0         1800.0
19  1250.0         1250.0

In [28]:
df.drop(columns=['price_display'], inplace=True)

In [29]:
bad_rows = df[
    ~df['fee'].isin(['Yes', 'No']) &
    df['fee'].notna()
]

bad_rows

,category,amenities,bathrooms,bedrooms,currency,fee,has_photo,pets_allowed,price,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
8808,Gym,USD,No,Thumbnail,"Cats,Dogs",1380,1380,Monthly,713.0,Lawrence,NJ,40.2659,-74.6959,RentDigs.com,1.568782e+09,NaN,NaN,NaN
33780,"Parking,Patio/Deck",USD,No,Thumbnail,NaN,2150,2150,Monthly,792.0,Los Angeles,CA,34.0432,-118.2509,RentDigs.com,1.568745e+09,NaN,NaN,NaN

In [30]:
bad_rows = df[
    ~df['fee'].isin(['Yes', 'No']) &
    df['fee'].notna()
]

print(len(bad_rows))

2

In [31]:
bad_rows = df[
    pd.to_numeric(df['currency'], errors='coerce').notna()
]

print(len(bad_rows))

0

In [32]:
bad_idx = df[
    ~df['fee'].isin(['Yes', 'No']) &
    df['fee'].notna()
].index

df_clean = df.drop(index=bad_idx)

In [33]:
print(df_clean.shape)
print(df.shape)

(99823, 18)
(99825, 18)

In [34]:
df_clean['bathrooms'] = pd.to_numeric(df_clean['bathrooms'], errors='coerce')
df_clean['bedrooms'] = pd.to_numeric(df_clean['bedrooms'], errors='coerce')
df_clean['square_feet'] = pd.to_numeric(df_clean['square_feet'], errors='coerce')

df_clean['latitude'] = pd.to_numeric(df_clean['latitude'], errors='coerce')
df_clean['longitude'] = pd.to_numeric(df_clean['longitude'], errors='coerce')

df_clean['time'] = pd.to_datetime(
    df_clean['time'],
    unit='s',
    errors='coerce'
)

In [35]:
print(df_clean.info())

print(
    df_clean[
        ~df_clean['fee'].isin(['Yes', 'No']) &
        df_clean['fee'].notna()
    ].shape
)

<class 'pandas.core.frame.DataFrame'>
Index: 99823 entries, 0 to 99825
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   category      99823 non-null  object
 1   amenities     99823 non-null  object
 2   bathrooms     99757 non-null  float64
 3   bedrooms      99696 non-null  float64
 4   currency      99820 non-null  object
 5   fee           99820 non-null  object
 6   has_photo     99820 non-null  object
 7   pets_allowed  39189 non-null  object
 8   price         99819 non-null  float64
 9   price_type    99820 non-null  object
 10  square_feet   99820 non-null  float64
 11  address       7943 non-null   object
 12  cityname      99518 non-null  object
 13  state         99518 non-null  object
 14  latitude      99795 non-null  float64
 15  longitude     99795 non-null  float64
 16  source        99820 non-null  object
 17  time          99820 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(6), object(11)
memory usage: 14.5+ MB
None
(0, 18)

In [36]:
df_clean = df_clean.drop(columns=['address'])

In [37]:
categorical_cols = [
    'category',
    'currency',
    'fee',
    'has_photo',
    'pets_allowed',
    'price_type',
    'cityname',
    'state',
    'source'
]

In [38]:
missing_pct = (
    df_clean.isna().mean()
    .mul(100)
    .sort_values(ascending=False)
)

print(missing_pct)

pets_allowed    60.741512
cityname         0.305541
state            0.305541
bedrooms         0.127225
bathrooms        0.066117
latitude         0.028050
longitude        0.028050
price            0.004007
price_type       0.003005
source           0.003005
fee              0.003005
currency         0.003005
has_photo        0.003005
time             0.003005
square_feet      0.003005
category         0.000000
amenities        0.000000
dtype: float64

In [39]:
df_clean.describe()

,bathrooms,bedrooms,price,square_feet,latitude,longitude,time
count,99757.000000,99696.000000,99819.000000,99820.000000,99795.000000,99795.000000,99820
mean,1.445332,1.727983,1527.224015,956.411691,36.950073,-91.562177,2019-06-04 23:08:14.181035776
min,1.000000,0.000000,100.000000,101.000000,19.573800,-159.369800,2018-12-07 09:20:18
25%,1.000000,1.000000,1014.000000,729.000000,33.749600,-104.791900,2019-02-22 10:36:12.750000128
50%,1.000000,2.000000,1350.000000,900.000000,37.229700,-84.562300,2019-09-17 18:31:31.500000
75%,2.000000,2.000000,1795.000000,1115.000000,39.953900,-77.585300,2019-09-18 00:38:45.249999872
max,9.000000,9.000000,52500.000000,50000.000000,64.833200,-68.778800,2019-12-26 20:17:05
std,0.546906,0.748941,903.638141,417.253229,4.599620,15.819296,NaN

In [40]:
df_clean[df_clean['price'] <= 0]

df_clean[df_clean['bedrooms'] < 0]

df_clean[df_clean['bathrooms'] < 0]

df_clean[df_clean['square_feet'] <= 0]

Empty DataFrame
Columns: [category, amenities, bathrooms, bedrooms, currency, fee, has_photo, pets_allowed, price, price_type, square_feet, cityname, state, latitude, longitude, source, time]
Index: []

In [41]:
df_clean['price'].describe(percentiles=[.01,.05,.95,.99])

count    99819.000000
mean      1527.224015
std        903.638141
min        100.000000
1%         545.000000
5%         699.000000
50%       1350.000000
95%       2924.000000
99%       4250.000000
max      52500.000000
Name: price, dtype: float64

In [42]:
df_clean.nlargest(20, 'price')[
    ['price', 'cityname', 'state', 'bedrooms', 'bathrooms', 'square_feet']
]

         price           cityname state  bedrooms  bathrooms  square_feet
6863   52500.0            Barstow    CA       0.0        1.0       1418.0
41235  40000.0        Los Angeles    CA       6.0        8.0       7145.0
17178  35000.0     West Hollywood    CA       4.0        4.0       2269.0
28084  35000.0     West Hollywood    CA       7.0        5.0       5586.0
41018  35000.0     West Hollywood    CA       6.0        7.5       6366.0
46120  33165.0  Pacific Palisades    CA       3.0        2.5       2211.0
38776  32000.0        Los Angeles    CA       6.0        9.0       5055.0
14447  30000.0   Snowmass Village    CO       5.0        5.5       5872.0
31326  29500.0             Venice    CA       3.0        3.0       4291.0
35337  29500.0        Los Angeles    CA       6.0        NaN      11000.0
38679  29000.0      Beverly Hills    CA       6.0        6.0       7213.0
3487   25000.0          Montecito    CA       6.0        8.0       8716.0
23621  25000.0      Playa Del Rey    CA       4.0        5.0       6881.0
41502  25000.0        Los Angeles    CA       5.0        7.0       6035.0
70348  25000.0     Bonita Springs    FL       4.0        4.5       5663.0
84179  24900.0        Los Angeles    CA       3.0        4.0       3217.0
23935  23000.0        Los Angeles    CA       3.0        3.5       3280.0
18372  20000.0     West Hollywood    CA       3.0        3.0       2866.0
6574   19500.0        Los Angeles    CA       4.0        5.0       5000.0
95578  19500.0      San Francisco    CA       4.0        5.0       4380.0

In [43]:
df_clean[df_clean['price'] > 10000][
    ['price', 'cityname', 'state', 'bedrooms', 'bathrooms', 'square_feet']
].sort_values('price', ascending=False)

         price        cityname state  bedrooms  bathrooms  square_feet
6863   52500.0         Barstow    CA       0.0        1.0       1418.0
41235  40000.0     Los Angeles    CA       6.0        8.0       7145.0
17178  35000.0  West Hollywood    CA       4.0        4.0       2269.0
41018  35000.0  West Hollywood    CA       6.0        7.5       6366.0
28084  35000.0  West Hollywood    CA       7.0        5.0       5586.0
...        ...             ...   ...       ...        ...          ...
37047  11000.0   Hermosa Beach    CA       4.0        4.5       2984.0
51572  11000.0       Hollywood    FL       5.0        3.0       3395.0
39775  11000.0   Beverly Hills    CA       2.0        3.0       2330.0
7446   10600.0     Los Angeles    CA       2.0        2.0       1636.0
94309  10379.0       Nashville    TN       3.0        2.5       2591.0

[72 rows x 6 columns]

In [44]:
df_clean['segment'] = np.where(df_clean['price'] > 10000, 'luxury', 'standard')

In [45]:
df_clean['has_photo'] = df['has_photo'].fillna('No')

df_clean['has_photo'] = df['has_photo'].apply(
    lambda x: 1 if str(x).lower() in ['yes', 'thumbnail'] else 0
)

In [46]:
df_clean['has_photo'].value_counts()

has_photo
1    90559
0     9264
Name: count, dtype: int64

In [47]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99823 entries, 0 to 99825
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   category      99823 non-null  object
 1   amenities     99823 non-null  object
 2   bathrooms     99757 non-null  float64
 3   bedrooms      99696 non-null  float64
 4   currency      99820 non-null  object
 5   fee           99820 non-null  object
 6   has_photo     99823 non-null  int64
 7   pets_allowed  39189 non-null  object
 8   price         99819 non-null  float64
 9   price_type    99820 non-null  object
 10  square_feet   99820 non-null  float64
 11  cityname      99518 non-null  object
 12  state         99518 non-null  object
 13  latitude      99795 non-null  float64
 14  longitude     99795 non-null  float64
 15  source        99820 non-null  object
 16  time          99820 non-null  datetime64[ns]
 17  segment       99823 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(10)
memory usage: 14.5+ MB

In [48]:
from pandas_gbq import to_gbq

to_gbq(
    df_clean,
    destination_table='ndata.apts_clean',
    project_id='my-capstone-498914',
    if_exists='replace'
)

100%|██████████| 1/1 [00:00<00:00, 9078.58it/s]

In [45]:
df_clean.to_csv('rental_housing_cleaned.csv', index=False)